const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#F5F3FF",
    foreground: "#1A1040",
    card: "#FFFFFF",
    cardForeground: "#1A1040",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#4C1D95",
    muted: "#F3F0FF",
    mutedForeground: "#6B6880",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD6FE",
    input: "#EDE9FE",
    success: "#10B981",
    gold: "#F59E0B",
    gradientBg: ["#F5F3FF", "#EDE9FE", "#F5F3FF"] as [string, string, string],
    gradientBg2: ["#F5F3FF", "#EDE9FE"] as [string, string],
  },
  dark: {
    text: "#F8F7FF",
    tint: "#A78BFA",
    background: "#0D0B1E",
    foreground: "#F8F7FF",
    card: "#1A1635",
    cardForeground: "#F8F7FF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1B38",
    secondaryForeground: "#C4B5FD",
    muted: "#2D2A4A",
    mutedForeground: "#9B99B8",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2A4A",
    input: "#2D2A4A",
    success: "#10B981",
    gold: "#F59E0B",
    gradientBg: ["#0D0B1E", "#1A0F3C", "#0D0B1E"] as [string, string, string],
    gradientBg2: ["#0D0B1E", "#1A0F3C"] as [string, string],
  },
  radius: 14,
};

export default colors;
